### ISSUE TITLE
DTG verify and replace existing rules

### ISSUE THREAD

**Issue by matzikitzoro** [rega-cev/Rega-ASI#13]
High level resistance: score at least 2
Intermediate resistance: score at least 1,5

+ Score 2: (A49G+S230R+R263K)
+ Score 1,5: (Q148H/K/R+L74I)
+ Score 1: Q148H/K/R, G118R, R263K;
+ Score 0,5: T66K, L74M, E92Q, G140A/C/S, I151L, S153F/Y, N155H/S/T
+ Score 0,25: A49G/P, T97A, F121Y, S147G, S230G/R

Completely new set of rules

**Comment by matzikitzoro** [comment]
ongoing, waiting for kristof feedback

**Comment by ktheyss** [comment]
hi fossie, i have no objections. 

However, let s put this specific example/problem on mail for discussion, like a screenshot?

**Comment by matzikitzoro** [comment]
I don't follow but I'll delete the comment anyway. It's not useful on github. It was for my own reference actually.
________________________________
Van: ktheyss<mailto:notifications@github.com>
Gestuur: ‎04/‎04/‎2016 17:55
Aan: rega-cev/Rega-ASI<mailto:Rega-ASI@noreply.github.com>
AA: Fossie Ferreira<mailto:matzikitzoro@gmail.com>
Onderwerp: Re: [rega-cev/Rega-ASI] DTG verify and replace existing rules (#13)

hi fossie, i have no objections.

However, let s put this specific example/problem on mail for discussion, like a screenshot?



> On 4 Apr 2016, at 15:56, Fossie Ferreira <notifications@github.com> wrote:
>
> ongoing, waiting for kristof feedback
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/rega-cev/Rega-ASI/issues/13#issuecomment-205304970>



---

**Comment by ktheyss** [comment]
:-) nevermind. but we need input on the new thing 1+1=3

**Comment by matzikitzoro** [comment]
done
